version: '2'
services:
    happy-hours:
        build: .
        expose:
            - "3000"
        volumes:
            - ./config:/usr/src/app/config
            - ./sessions:/usr/src/app/sessions
            - ./logs:/usr/src/app/logs
    proxy:
        image: zzrot/alpine-caddy
        ports:
            -   "3000:3000"
        volumes:
            -   ./Caddyfile:/etc/Caddyfile
            -   ./.caddy:/root/.caddy
            -   ./public:/var/www/html
