version: '2'
services:
    happy-hours:
        image: gleis21/happy-hours:latest
        depends_on:
            - redis
    proxy:
        image: adriel/caddy:0.10.13
        depends_on:
            - happy-hours
    redis:
        image: redis:alpine
