version: '2'
services:
    happy-hours:
        build: .
        expose:
            - "3000"
        volumes:
            - .:/usr/src/app
    proxy:
        image: zzrot/alpine-caddy
        ports:
            -   "80:80"
        volumes:
            -   ./Caddyfile:/etc/Caddyfile
            -   ./.caddy:/root/.caddy
            -   ./public:/var/www/html
